name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    
    - name: make
      run: make -f /dev/null 24it3
    - name: check executable
      run: bash -c "[[ -x 24it3 ]]"
    
